- name: extract home tar balls for users
  unarchive:
    remote_src: yes
    src: "{{ item.tar_ball }}"
    dest: "/home/{{ item.local_user_name }}"
  become_user: "{{ item.local_user_name }}"
  with_items: "{{ local_users_tarballs }}"
  when: local_users_tarballs is defined
