software_config:
  conky:
  - conky_env_iface: enp0s8
    conky_env_name: ECX
    conky_user_name: bwatts
    conky_vpn_iface: utun0
user_config:
- user_crypt_passwd: $6$gxPnXTMb$4Je18w87.IdftVy51oz58bM8/2i5CnakbrH3beprPzUm6w/oA1A21qbUyM.1XEQXWfhhn.2xZZnn0hTG5581R1
  user_dot_files_repo: https://github.com/bw31642/dotfiles.git
  user_gcos: Brian Watts
  user_home_tar_ball: http://wattsy.duckdns.org:8888/files/bwatts-home.tar
  user_name: bwatts
  user_secgrps:
  - vboxsf
  - audio
  - adm
  - sudo
  - video
  user_ssh_auth_keys_file: bwatts.authorized_keys
  user_ssh_dir: /home/bwatts/.ssh
